export const UPDATE_SEARCH_TERMS = 'UPDATE_SEARCH_TERMS';
export const SUBMIT_SEARCH_TERMS = 'SUBMIT_SEARCH_TERMS';
export const UPDATE_SONG_LIST = 'UPDATE_SONG_LIST';
export const SET_IS_LOADING = 'SET_IS_LOADING';